In [1]:
import pandas as pd
data=pd.read_csv("movies.csv")
data.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,tt0036868,8.1,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.8,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,tt0042593,7.9,30924.0,8.273,7.6

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9871 entries, 0 to 9870
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    9871 non-null   object
 1   title                 9871 non-null   object
 2   type                  9871 non-null   object
 3   description           9752 non-null   object
 4   release_year          9871 non-null   int64
 5   age_certification     3384 non-null   object
 6   runtime               9871 non-null   int64
 7   genres                9871 non-null   object
 8   production_countries  9871 non-null   object
 9   seasons               1357 non-null   float64
 10  imdb_id               9204 non-null   object
 11  imdb_score            8850 non-null   float64
 12  imdb_votes            8840 non-null   float64
 13  tmdb_popularity       9324 non-null   float64
 14  tmdb_score            7789 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 1.1+ MB

#### What is the average imdb score for movies?

In [10]:
grp1=data.groupby(["type"])["imdb_score"].mean()
print(grp1)

type
MOVIE    5.803110
SHOW     7.118353
Name: imdb_score, dtype: float64

#### How many null values are there in the ‘Age_certification’ column.

In [17]:
nullvalues=data["age_certification"].isna().sum()
print("The null values in the column the age_certification is:",nullvalues)

The null values in the column the age_certification is: 6487

#### How many numeric valued columns are present?

In [22]:
import numpy as np
numeric=data.select_dtypes(include=np.number)
print("The number of numeric column is:",len(numeric.columns))

The number of numeric column is: 7

#### Write the code to display the movies released after the year 2000. How many movies were released after the year 2000?

In [77]:
column=data["release_year"]
count=column[column>2000].count()
print("The movies after 2000 are:",count)

The movies after 2000 are: 7066

#### counting the null values:

In [28]:
print(data.isna().sum())

id                         0
title                      0
type                       0
description              119
release_year               0
age_certification       6487
runtime                    0
genres                     0
production_countries       0
seasons                 8514
imdb_id                  667
imdb_score              1021
imdb_votes              1031
tmdb_popularity          547
tmdb_score              2082
dtype: int64

#### After dropping all the null values in the dataset, how many rows remain?

In [27]:
print("The number of rows before removing null values:",len(data.index))

The number of rows before removing null values: 9871

In [30]:
newdf=data.dropna()
print("The number of rows after removing null values:",len(newdf.index))

The number of rows after removing null values: 581

#### Out of these rows, how many movies released after 2020?

In [78]:
column=newdf["release_year"]
count=column[column>2020].count()
print("The movies after 2020 are:",count)

The movies after 2020 are: 48

#### What is the average tmdb_popularity for movies containing ‘Comedy’ as a genre?

In [34]:
grp2=newdf.groupby(["genres"])["tmdb_popularity"].mean()
print(grp2)

genres
['action', 'animation', 'comedy', 'crime']                           1.101570
['action', 'animation', 'comedy', 'family', 'scifi', 'european']    29.598000
['action', 'animation', 'comedy', 'romance']                        52.173000
['action', 'animation', 'drama', 'history']                         12.306000
['action', 'animation', 'family', 'comedy', 'crime', 'european']    25.766000
                                                                      ...
['war', 'thriller', 'action', 'drama']                              45.833000
['western', 'drama', 'thriller']                                    62.728000
['western', 'drama', 'war', 'history']                               9.662000
['western', 'drama']                                                15.796000
[]                                                                   4.625667
Name: tmdb_popularity, Length: 335, dtype: float64

In [71]:
newdf[(newdf["genres"].str.contains("comedy"))].describe().T.loc["tmdb_popularity"].loc["mean"]

23.199940124481316

#### In how many movie descriptions, the word ‘novel’ appears?

In [53]:
 newdf.loc[newdf['description'].str.contains("novel", case=False)]

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
2402,ts25096,Little Men,SHOW,Little Men is a Canadian television show that ...,1998,TV-PG,45,"['drama', 'family']","['CA', 'US']",2.0,tt0179029,7.4,346.0,6.593,9.0
3029,ts32764,WordWorld,SHOW,WordWorld is an Emmy Award-winning children's ...,2007,TV-Y,29,"['animation', 'family']",['US'],3.0,tt1097633,6.6,414.0,4.297,7.0
3076,ts38010,MegaStructures,SHOW,MegaStructures is a documentary television ser...,2004,TV-PG,59,['documentation'],['US'],18.0,tt0446850,7.3,998.0,6.549,7.6
3333,ts43355,"Sandra, The Fairytale Detective",SHOW,"Sandra, The Fairytale Detective is a Spanish T...",2009,TV-G,14,"['animation', 'comedy', 'european']",['ES'],1.0,tt1832767,8.2,47.0,1.056,8.3
4592,ts22418,Utopia,SHOW,The Utopia Experiments is a legendary graphic...,2013,TV-MA,51,"['scifi', 'drama', 'thriller', 'european']",['GB'],2.0,tt2384811,8.4,45874.0,30.354,8.0
4593,ts4647,The Affair,SHOW,The Affair explores the emotional effects of a...,2014,TV-MA,59,['drama'],['US'],5.0,tt2699110,7.9,44661.0,22.710,6.6
4636,ts20723,Spies of Warsaw,SHOW,A military attaché at the French embassy is dr...,2013,TV-14,45,"['drama', 'action', 'romance', 'war', 'european']",['GB'],1.0,tt2343137,6.8,2333.0,8.912,6.5
5289,ts14841,Bosch,SHOW,Based on Michael Connelly's best-selling novel...,2015,TV-MA,46,"['crime', 'drama']",['US'],7.0,tt3502248,8.5,64854.0,63.676,8.0
5303,ts21882,The Man in the High Castle,SHOW,Explore what it would be like if the Allied Po...,2015,TV-MA,55,"['drama', 'scifi', 'thriller']",['US'],4.0,tt1740299,8.0,96965.0,84.623,7.5
5358,ts38814,I Love Dick,SHOW,Adapted from the lauded feminist novel and set...,2016,TV-MA,26,"['comedy', 'romance']",['US'],1.0,tt5478730,6.2,4389.0,5.782,5.8
6156,ts12314,American Gods,SHOW,An ex-con becomes the traveling partner of a c...,2017,TV-MA,54,"['scifi', 'drama', 'fantasy']",['US'],3.0,tt1898069,7.7,84311.0,54.759,7.1
6175,ts57406,Get Shorty,SHOW,Miles Daly works as muscle for a murderous cri...,2017,TV-MA,56,"['crime', 'comedy']",['US'],3.0,tt5761496,8.2,7058.0,25.307,6.9
7441,ts115157,Dublin Murders,SHOW,Crime series based on the novels by Tana French.,2019,TV-MA,57,"['crime', 'drama', 'thriller']",['GB'],1.0,tt7768192,7.1,10154.0,11.012,7.1
7466,ts80485,Utopia,SHOW,A group of young adults who met online are mer...,2020,TV-MA,49,"['action', 'drama', 'scifi', 'thriller']",['US'],1.0,tt8303474,6.7,13568.0,30.979,7.4
9220,ts218566,The Vineyard,SHOW,"Based on the novel by María Dueñas, a romantic...",2021,TV-14,50,"['drama', 'history', 'romance']",['ES'],1.0,tt10681240,7.0,689.0,1.400,7.5

In [54]:
print("Novel word appears 15 times in movie description")

Novel word appears 15 times in movie description

#### How many unique production countries are present in the data?

In [57]:
grp3=newdf.groupby("production_countries")
grp3.first()

,id,title,type,description,release_year,age_certification,runtime,genres,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
production_countries,,,,,,,,,,,,,,
"['AT', 'GB', 'US']",ts26966,On Death Row,SHOW,A two part series on an inside look at a maxim...,2012,TV-14,49,"['documentation', 'drama', 'horror']",2.0,tt8260704,7.9,1195.0,2.073,7.4
['AU'],ts21352,Home and Away,SHOW,Home and Away is set in the fictional town of ...,1988,TV-14,24,"['drama', 'romance']",35.0,tt0094481,5.1,5942.0,77.918,6.2
['BR'],ts240318,Lov3,SHOW,"Siblings Ana, Sofia and Beto try to outrun con...",2022,TV-MA,34,"['romance', 'comedy', 'drama']",1.0,tt12279642,5.9,107.0,10.255,10.0
"['CA', 'AU', 'US']",ts31759,The Saddle Club,SHOW,The Saddle Club is a children's television ser...,2001,TV-Y,25,['family'],3.0,tt0278876,5.9,1024.0,14.446,6.2
"['CA', 'FR']",ts17762,Babar,SHOW,Babar is a Canadian/French/Japanese animated t...,1989,TV-G,24,"['animation', 'comedy', 'drama', 'family', 'fa...",6.0,tt0156200,6.6,5.0,3.894,6.7
"['CA', 'GB']",ts20389,Primeval: New World,SHOW,A North American spin-off of the hit U.K. tele...,2012,TV-14,45,"['action', 'drama', 'scifi']",1.0,tt2295955,6.5,4565.0,13.861,6.6
"['CA', 'US', 'DK', 'JP']",ts17364,Chaotic,SHOW,Chaotic is an American-Canadian animated fanta...,2006,TV-Y7,21,"['scifi', 'animation', 'family', 'fantasy']",3.0,tt0850635,6.4,561.0,1.400,9.0
"['CA', 'US']",ts7221,Arthur,SHOW,The show revolves around the lives of 8-year-o...,1996,TV-Y,26,"['comedy', 'fantasy', 'scifi', 'animation', 'd...",25.0,tt0169414,7.4,14014.0,24.827,7.0
['CA'],ts41693,The Kids in the Hall,SHOW,The Kids in the Hall is a Canadian sketch come...,1989,TV-MA,24,['comedy'],6.0,tt0096626,8.4,9794.0,14.945,7.7
"['CH', 'GB']",ts22821,Pingu,SHOW,Playful penguin Pingu lives with his family in...,1986,TV-Y,9,"['comedy', 'family', 'animation', 'european']",6.0,tt0100366,7.4,6678.0,37.099,6.8
['CL'],ts236482,El Presidente,SHOW,The head of a small Chilean football club beco...,2020,TV-MA,56,"['drama', 'documentation', 'sport']",1.0,tt14656362,8.4,20.0,21.045,7.2
['CN'],ts53534,Ip Man,SHOW,Grandmaster Ip Man was born in a time of turbu...,2013,TV-PG,49,['action'],2.0,tt3969094,5.6,174.0,4.393,7.0
['DE'],ts42942,Nazi Underworld,SHOW,Adolf Hitler pretended to be poor but amassed ...,2011,TV-14,47,"['documentation', 'history', 'war', 'european']",2.0,tt2098173,7.1,81.0,1.791,5.7
"['DK', 'US']",ts20458,Ninjago: Masters of Spinjitzu,SHOW,"When the fate of their world, Ninjago, is chal...",2012,TV-Y7,17,"['scifi', 'comedy', 'family', 'fantasy', 'anim...",15.0,tt1871731,7.2,4519.0,60.536,7.8
['ES'],ts43355,"Sandra, The Fairytale Detective",SHOW,"Sandra, The Fairytale Detective is a Spanish T...",2009,TV-G,14,"['animation', 'comedy', 'european']",1.0,tt1832767,8.2,47.0,1.056,8.3
"['FR', 'GB', 'US', 'CA']",ts22130,Rolie Polie Olie,SHOW,Rolie Polie Olie was a children's television s...,1998,TV-Y,21,"['animation', 'comedy', 'family', 'fantasy', '...",6.0,tt0172049,6.3,2861.0,8.697,6.8
"['FR', 'US', 'DE']",ts10058,Cosmic Quantum Ray,SHOW,"""Cosmic Quantum Ray"" is a zany comedy-action-a...",2010,TV-G,22,"['action', 'family', 'animation', 'documentati...",1.0,tt1398547,5.6,44.0,3.408,10.0
"['FR', 'US']",ts21615,Totally Spies!,SHOW,Totally Spies! depicts three girlfriends 'with...,2001,TV-Y7,22,"['action', 'animation', 'comedy', 'family', 's...",6.0,tt0283226,7.1,10214.0,29.598,7.4
['FR'],ts43880,LoliRock,SHOW,"Follow the journey of young Iris, a spirited t...",2014,TV-Y,21,"['music', 'family', 'animation', 'action', 'co...",4.0,tt4506998,7.3,448.0,6.423,9.2
"['GB', 'NL']",ts192297,Morphle,SHOW,Mila's dad runs the only magic pet store in th...,2019,TV-Y,6,"['animation', 'family']",5.0,tt10087694,5.1,77.0,2.388,10.0
"['GB', 'US']",ts35948,Wheeler Dealers,SHOW,Experienced car dealer Mike Brewer is joined b...,2003,TV-PG,38,"['documentation', 'reality', 'european']",22.0,tt14307260,8.2,3143.0,23.523,7.3
['GB'],ts46032,Gardeners' World,SHOW,Gardeners' World is a long-running BBC Televis...,1968,TV-G,54,['documentation'],22.0,tt0260618,8.3,243.0,10.063,8.5
['IE'],ts26038,Pajanimals,SHOW,Jim Henson's Pajanimals is a children's TV ser...,2008,TV-PG,13,['family'],3.0,tt1419888,6.7,100.0,1.441,10.0
['IN'],ts85612,Mirzapur,SHOW,The iron-fisted Akhandanand Tripathi is a mill...,2018,TV-MA,50,"['crime', 'action', 'drama', 'thriller']",2.0,tt6473300,8.5,67946.0,16.213,8.2
['IT'],ts22318,Winx Club,SHOW,"In a magical universe, witches, warriors begin...",2004,TV-G,23,"['action', 'comedy', 'family', 'fantasy', 'ani...",8.0,tt3233214,6.2,6700.0,25.162,8.2
['JP'],ts21930,Lupin the Third,SHOW,Arsene Lupin III is the grandson of the master...,1971,TV-14,23,"['scifi', 'animation', 'action', 'comedy', 'cr...",6.0,tt0159175,7.9,2116.0,45.829,8.0
['KR'],ts21688,Boys Over Flowers,SHOW,A working class girl winds up at an exclusive ...,2009,TV-14,64,"['comedy', 'drama', 'romance']",1.0,tt1370334,7.9,11579.0,75.209,8.3
['MX'],ts10848,Diablo Guardián,SHOW,"The story of Violetta, a young woman who flees...",2018,TV-MA,40,"['drama', 'action']",2.0,tt6121710,6.2,658.0,23.482,6.7
['NZ'],ts43866,Serial Killers,SHOW,This 7-part season is filled with expert inter...,2009,TV-MA,53,"['documentation', 'crime', 'drama', 'horror']",1.0,tt10534980,7.4,26.0,1.134,6.0
['PR'],ts243572,Súbete a mi Moto,SHOW,The Story behind the the iconic boy band Menud...,2020,TV-14,44,['drama'],1.0,tt12248706,5.9,264.0,19.136,7.6
"['US', 'AU']",ts13686,Farscape,SHOW,A freak accident during an experimental space ...,1999,TV-14,48,"['scifi', 'action', 'drama']",5.0,tt0187636,8.3,36483.0,28.242,7.9
"['US', 'BE', 'CA', 'FR']",ts9770,The Adventures of Tintin,SHOW,"Travel with Tintin, the young and intrepid Bel...",1991,TV-Y7,23,"['action', 'animation', 'family', 'comedy', 'c...",7.0,tt0179552,8.2,17859.0,25.766,8.0
"['US', 'CA', 'GB']",ts21742,My Dad the Rock Star,SHOW,My Dad the Rock Star is a Canadian animated te...,2003,TV-Y,24,"['animation', 'family', 'comedy', 'music']",2.0,tt0388625,5.1,404.0,2.960,5.5
"['US', 'CA']",ts27730,Kratts' Creatures,SHOW,Kratts' Creatures is a children's television p...,1996,TV-Y,27,['family'],1.0,tt0159885,8.2,251.0,1.960,8.3
"['US', 'ES']",ts329879,MotoGP Unlimited,SHOW,"The eight-episode series, filmed by The Mediap...",2022,TV-Y7,48,['documentation'],1.0,tt18396468,7.9,121.0,5.128,8.0
"['US', 'FR']",ts46067,Sonic Underground,SHOW,"Sonic, Sonia, and Manic are the children of Qu...",1999,TV-Y7,22,"['action', 'thriller', 'fantasy', 'music', 'sc...",1.0,tt0230804,6.1,2943.0,38.567,6.9
"['US', 'GB', 'CA']",ts11794,The Cat in the Hat Knows a Lot About That!,SHOW,"The Cat in the Hat is back -- and this time, h...",2013,TV-Y,19,"['animation', 'fantasy', 'scifi', 'comedy', 'f...",3.0,tt1699440,6.4,620.0,5.963,7.8
"['US', 'GB']",ts22065,Secret Diary of a Call Girl,SHOW,It's her business doing pleasure with you. A w...,2007,TV-MA,23,"['drama', 'european']",4.0,tt1000734,7.4,13414.0,12.327,7.0
"['US', 'JP']",ts33633,Voltron: Defender of the Universe,SHOW,Voltron is the name of a giant robot in an ani...,1984,TV-Y7,24,"['scifi', 'family', 'animation']",3.0,tt0086824,7.9,4740.0,14.719,8.0
['US'],ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",26.0,tt0850645,8.6,1092.0,15.424,7.6
[],ts53581,Superbook,SHOW,Chris Quantum is your typical Middle School st...,2011,TV-G,26,"['animation', 'family', 'fantasy']",5.0,tt1740717,6.4,260.0,16.625,8.7

In [69]:
newdf.nunique()

id                      581
title                   579
type                      1
description             581
release_year             53
age_certification         6
runtime                  70
genres                  335
production_countries     41
seasons                  29
imdb_id                 581
imdb_score               56
imdb_votes              553
tmdb_popularity         564
tmdb_score               58
dtype: int64

## Use the student_1 and student_2 excel files to answer the below question

In [58]:
df1=pd.read_excel("student_1.xlsx")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   num          58 non-null     int64
 1   11 Jul 2022  58 non-null     object
 2   12 Jul 2022  58 non-null     object
 3   13 Jul 2022  58 non-null     object
 4   14 Jul 2022  58 non-null     object
 5   19 Jul 2022  58 non-null     object
 6   21 Jul 2022  58 non-null     object
 7   26 Jul 2022  58 non-null     object
dtypes: int64(1), object(7)
memory usage: 3.8+ KB

In [59]:
df2=pd.read_excel("student_2.xlsx")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   roll_number          333 non-null    int64
 1   Program              333 non-null    object
 2   Registration Number  333 non-null    int64
dtypes: int64(2), object(1)
memory usage: 7.9+ KB

In [61]:
newdata=pd.merge(df1,df2,how="inner",left_on="num",right_on="roll_number")
newdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 0 to 56
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   num                  57 non-null     int64
 1   11 Jul 2022          57 non-null     object
 2   12 Jul 2022          57 non-null     object
 3   13 Jul 2022          57 non-null     object
 4   14 Jul 2022          57 non-null     object
 5   19 Jul 2022          57 non-null     object
 6   21 Jul 2022          57 non-null     object
 7   26 Jul 2022          57 non-null     object
 8   roll_number          57 non-null     int64
 9   Program              57 non-null     object
 10  Registration Number  57 non-null     int64
dtypes: int64(3), object(8)
memory usage: 5.3+ KB

In [64]:
newdata.head()

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022,roll_number,Program,Registration Number
0,21110077,P,P,P,P,P,P,P,21110077,B.Tech CSE (IoT),21011102006
1,21110219,P,P,P,A,P,P,P,21110219,B.Tech CSE (IoT),21011102002
2,21110278,P,P,P,P,P,P,P,21110278,B.Tech CSE (IoT),21011102057
3,21110451,P,P,P,P,P,P,A,21110451,B.Tech CSE (IoT),21011102017
4,21110103,P,P,P,P,P,P,P,21110103,B.Tech CSE (IoT),21011102020